services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master1000geo
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://root:root@database:3306/tennis_db?serverVersion=8.0

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tennis_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
